name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup do NodeJS
        uses: actions/setupe-node@v3.0.0
        with:
          node-version: 20.13.1
    
